/*
	Cine Studio - Server side timeline render

	Renders the whole timeline on the host with ffmpeg (no browser
	involvement). The frontend serializes the project into a render
	spec (see ffmpeg.renderTimeline in the AGI docs), which references
	media by virtual path; title / color clips arrive as pre-rendered
	PNG stills uploaded next to the export.

	Parameters:
	  spec   - render spec JSON string
	  taskId - unique task ID generated by the frontend ([A-Za-z0-9_-])
	  output - virtual path of the output file (.mp4 or .webm)

	Progress can be polled with backend/renderprogress.js using the
	same taskId. The request stays open until the render finishes, but
	the task file below is the source of truth for completion, so the
	frontend survives a dropped connection.
*/

requirelib("filelib");

function fail(msg) {
	sendJSONResp(JSON.stringify({ success: false, error: msg }));
}

function main() {
	var hasFFmpeg = false;
	try {
		hasFFmpeg = requirelib("ffmpeg");
	} catch (e) {
		hasFFmpeg = false;
	}
	if (!hasFFmpeg) {
		fail("ffmpeg is not available on this host");
		return;
	}

	if (typeof(spec) == "undefined" || typeof(taskId) == "undefined" || typeof(output) == "undefined") {
		fail("spec, taskId and output parameters are required");
		return;
	}
	if (!taskId.match(/^[A-Za-z0-9_\-]+$/)) {
		fail("invalid taskId");
		return;
	}
	var lower = output.toLowerCase();
	if (lower.lastIndexOf(".mp4") != lower.length - 4 && lower.lastIndexOf(".webm") != lower.length - 5) {
		fail("output must be a .mp4 or .webm file");
		return;
	}

	var taskDir = "tmp:/cinestudio";
	if (!filelib.fileExists(taskDir)) {
		filelib.mkdir(taskDir);
	}
	var taskFile = taskDir + "/" + taskId + ".task.json";
	var progressFile = taskDir + "/" + taskId + ".progress.json";

	var task = {
		id: taskId,
		output: output,
		status: "running",
		error: "",
		created_at: Date.now()
	};
	filelib.writeFile(taskFile, JSON.stringify(task));

	var ok = false;
	var errMsg = "";
	try {
		ok = ffmpeg.renderTimeline(spec, output, progressFile);
	} catch (e) {
		errMsg = e.toString();
		ok = false;
	}

	task.status = ok ? "completed" : "failed";
	task.error = errMsg;
	task.finished_at = Date.now();
	filelib.writeFile(taskFile, JSON.stringify(task));

	sendJSONResp(JSON.stringify({
		success: ok,
		taskId: taskId,
		output: output,
		error: errMsg
	}));
}

main();
