package main

// cocoLabels maps YOLOv5 COCO class index (0-79) to a human-readable label.
var cocoLabels = [80]string{
	"person", "bicycle", "car", "motorcycle", "airplane",
	"bus", "train", "truck", "boat", "traffic light",
	"fire hydrant", "stop sign", "parking meter", "bench", "bird",
	"cat", "dog", "horse", "sheep", "cow",
	"elephant", "bear", "zebra", "giraffe", "backpack",
	"umbrella", "handbag", "tie", "suitcase", "frisbee",
	"skis", "snowboard", "sports ball", "kite", "baseball bat",
	"baseball glove", "skateboard", "surfboard", "tennis racket", "bottle",
	"wine glass", "cup", "fork", "knife", "spoon",
	"bowl", "banana", "apple", "sandwich", "orange",
	"broccoli", "carrot", "hot dog", "pizza", "donut",
	"cake", "chair", "couch", "potted plant", "bed",
	"dining table", "toilet", "tv", "laptop", "mouse",
	"remote", "keyboard", "cell phone", "microwave", "oven",
	"toaster", "sink", "refrigerator", "book", "clock",
	"vase", "scissors", "teddy bear", "hair drier", "toothbrush",
}

// cocoPhotoTag maps a COCO label to a search-friendly photo tag.
// Classes not present here are dropped (too generic or uninteresting for photo search).
var cocoPhotoTag = map[string]string{
	"person":         "people",
	"bicycle":        "bicycle",
	"car":            "vehicle",
	"motorcycle":     "motorcycle",
	"airplane":       "airplane",
	"bus":            "vehicle",
	"train":          "train",
	"truck":          "vehicle",
	"boat":           "boat",
	"traffic light":  "street",
	"fire hydrant":   "street",
	"stop sign":      "street",
	"bench":          "outdoor",
	"bird":           "bird",
	"cat":            "cat",
	"dog":            "dog",
	"horse":          "horse",
	"sheep":          "animal",
	"cow":            "animal",
	"elephant":       "animal",
	"bear":           "animal",
	"zebra":          "animal",
	"giraffe":        "animal",
	"backpack":       "outdoor",
	"umbrella":       "outdoor",
	"handbag":        "fashion",
	"tie":            "fashion",
	"suitcase":       "travel",
	"frisbee":        "sports",
	"skis":           "sports",
	"snowboard":      "sports",
	"sports ball":    "sports",
	"kite":           "outdoor",
	"baseball bat":   "sports",
	"baseball glove": "sports",
	"skateboard":     "sports",
	"surfboard":      "sports",
	"tennis racket":  "sports",
	"bottle":         "food",
	"wine glass":     "food",
	"cup":            "food",
	"bowl":           "food",
	"banana":         "food",
	"apple":          "food",
	"sandwich":       "food",
	"orange":         "food",
	"broccoli":       "food",
	"carrot":         "food",
	"hot dog":        "food",
	"pizza":          "food",
	"donut":          "food",
	"cake":           "food",
	"chair":          "indoor",
	"couch":          "indoor",
	"potted plant":   "nature",
	"bed":            "indoor",
	"dining table":   "indoor",
	"tv":             "indoor",
	"laptop":         "indoor",
	"cell phone":     "indoor",
	"book":           "indoor",
	"clock":          "indoor",
	"vase":           "indoor",
	"teddy bear":     "indoor",
}
